// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvN5rpxXefxaPQqgWyBtpaG9kZKBIWCyk',
    appId: '1:96016208807:web:33331e0f88f695d0cc5c82',
    messagingSenderId: '96016208807',
    projectId: 'flutter-e-commerce-app-93d81',
    authDomain: 'flutter-e-commerce-app-93d81.firebaseapp.com',
    databaseURL: 'https://flutter-e-commerce-app-93d81-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-e-commerce-app-93d81.appspot.com',
    measurementId: 'G-0070YY2WDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6b3IlpYCV3u_55xy-UfAcJAiJRnuUHhc',
    appId: '1:96016208807:android:1bd3a1e72dec637bcc5c82',
    messagingSenderId: '96016208807',
    projectId: 'flutter-e-commerce-app-93d81',
    databaseURL: 'https://flutter-e-commerce-app-93d81-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-e-commerce-app-93d81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3VhKK46Do72cBJF2Ho94Qrqyp04eL7HM',
    appId: '1:96016208807:ios:352fb13fbb3c3b81cc5c82',
    messagingSenderId: '96016208807',
    projectId: 'flutter-e-commerce-app-93d81',
    databaseURL: 'https://flutter-e-commerce-app-93d81-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-e-commerce-app-93d81.appspot.com',
    iosClientId: '96016208807-a0ac9c9lhufsqe4qpq3j82f5n5mdkkhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAdminWeb',
  );
}
