// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy0q9DhMt6PFuYHpLaELKmXbUC0lUdgZc',
    appId: '1:1029361731735:web:52a1293f80a214287f41d2',
    messagingSenderId: '1029361731735',
    projectId: 'women-safety-app-67951',
    authDomain: 'women-safety-app-67951.firebaseapp.com',
    databaseURL: 'https://women-safety-app-67951-default-rtdb.firebaseio.com',
    storageBucket: 'women-safety-app-67951.appspot.com',
    measurementId: 'G-44Y32BETVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh8A-Pqdd6m2-h70dSBArjMANcAJnB5Co',
    appId: '1:1029361731735:android:978f99ed683be2f67f41d2',
    messagingSenderId: '1029361731735',
    projectId: 'women-safety-app-67951',
    databaseURL: 'https://women-safety-app-67951-default-rtdb.firebaseio.com',
    storageBucket: 'women-safety-app-67951.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy0q9DhMt6PFuYHpLaELKmXbUC0lUdgZc',
    appId: '1:1029361731735:web:00e596952755900a7f41d2',
    messagingSenderId: '1029361731735',
    projectId: 'women-safety-app-67951',
    authDomain: 'women-safety-app-67951.firebaseapp.com',
    databaseURL: 'https://women-safety-app-67951-default-rtdb.firebaseio.com',
    storageBucket: 'women-safety-app-67951.appspot.com',
    measurementId: 'G-40FZ9MK6P6',
  );
}
