// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy0q9DhMt6PFuYHpLaELKmXbUC0lUdgZc',
    appId: '1:1029361731735:web:9fbbb18b8374f8f57f41d2',
    messagingSenderId: '1029361731735',
    projectId: 'women-safety-app-67951',
    authDomain: 'women-safety-app-67951.firebaseapp.com',
    databaseURL: 'https://women-safety-app-67951-default-rtdb.firebaseio.com',
    storageBucket: 'women-safety-app-67951.appspot.com',
    measurementId: 'G-4SW6R729GX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh8A-Pqdd6m2-h70dSBArjMANcAJnB5Co',
    appId: '1:1029361731735:android:26d3f4b99d5754157f41d2',
    messagingSenderId: '1029361731735',
    projectId: 'women-safety-app-67951',
    databaseURL: 'https://women-safety-app-67951-default-rtdb.firebaseio.com',
    storageBucket: 'women-safety-app-67951.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM_ffMStWf4m6w5bM5zvM02K09-2MhqA0',
    appId: '1:1029361731735:ios:05ba43e976a575de7f41d2',
    messagingSenderId: '1029361731735',
    projectId: 'women-safety-app-67951',
    databaseURL: 'https://women-safety-app-67951-default-rtdb.firebaseio.com',
    storageBucket: 'women-safety-app-67951.appspot.com',
    androidClientId: '1029361731735-0ucrsmm6ru4lpv198ka9h7klgl0mmt61.apps.googleusercontent.com',
    iosClientId: '1029361731735-jn0us87ffaqdqtj5254uacfcn314082o.apps.googleusercontent.com',
    iosBundleId: 'com.example.womenSafetyDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM_ffMStWf4m6w5bM5zvM02K09-2MhqA0',
    appId: '1:1029361731735:ios:05ba43e976a575de7f41d2',
    messagingSenderId: '1029361731735',
    projectId: 'women-safety-app-67951',
    databaseURL: 'https://women-safety-app-67951-default-rtdb.firebaseio.com',
    storageBucket: 'women-safety-app-67951.appspot.com',
    androidClientId: '1029361731735-0ucrsmm6ru4lpv198ka9h7klgl0mmt61.apps.googleusercontent.com',
    iosClientId: '1029361731735-jn0us87ffaqdqtj5254uacfcn314082o.apps.googleusercontent.com',
    iosBundleId: 'com.example.womenSafetyDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy0q9DhMt6PFuYHpLaELKmXbUC0lUdgZc',
    appId: '1:1029361731735:web:cc0af0b8f4101bcb7f41d2',
    messagingSenderId: '1029361731735',
    projectId: 'women-safety-app-67951',
    authDomain: 'women-safety-app-67951.firebaseapp.com',
    databaseURL: 'https://women-safety-app-67951-default-rtdb.firebaseio.com',
    storageBucket: 'women-safety-app-67951.appspot.com',
    measurementId: 'G-4GH9C2MXY3',
  );

}